
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uid=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2),KEY='personal-orbit-v1',copy=v=>JSON.parse(JSON.stringify(v));
const defaults={version:1,profile:{name:'待填写姓名。',intro:'在声音里收集想象，在电影里走进未知。\n这里，留给那些还在生长的构思。\n个人介绍待填写 · 当前为示例开场',about:'这里是关于我的一小段留白。\n可以写下你的兴趣、创作习惯，\n以及最近让你感到好奇的事。\n\n这段自我介绍等待你来完成。',contact:'联系方式待填写 · 可以在本地管理中编辑。'},categories:[{id:'c1',title:'氛围 / Ambient',scope:'music',visible:true},{id:'c2',title:'电子 / Electronic',scope:'music',visible:true},{id:'c3',title:'心理恐怖',scope:'reviews',visible:true},{id:'c4',title:'超自然',scope:'reviews',visible:true}],music:[{id:'m1',title:'凌晨的潮汐',category:'c1',body:'示例构思：让一段缓慢起伏的合成器，像潮汐一样靠近又退去。低频不必很重，留一点空间给房间里自然的声音。\n\n结构笔记：\n开场 — 一层柔软的底噪。\n发展 — 稀疏的钢琴音符逐渐加入。\n结尾 — 去掉节拍，只留下呼吸般的氛围。\n\n这是一份演示用音乐构思，不是已经发布的作品。',note:'构思笔记 · 尚无音频',visible:true},{id:'m2',title:'轨道之外',category:'c2',body:'示例构思：一组不完全对齐的短音序，在循环里慢慢形成新的节奏。用轻盈的电子音色，写一种走出习惯的感觉。\n\n声音方向：颗粒合成、柔和的低频、少量空间混响。\n状态：只有概念文字，未附音频。',note:'灵感草稿 · 尚无音频',visible:true},{id:'m3',title:'给明天的留白',category:'c1',body:'示例构思：一首不急着抵达高潮的作品。让每一个音符都能完整落下，把静默也当作编曲的一部分。\n\n可以从木质打击乐与一段短旋律开始，试着保留第一次记录时不够完美的质感。\n\n此内容仅用于展示音乐构思页面。',note:'声音实验 · 尚无音频',visible:true}],reviews:[{id:'r1',title:'那扇门后，真的有人吗？',film:'影片名称待填写',category:'c3',rating:'待评分',body:'【影评写作示例 · 非真实观影评价】\n\n比起突然出现的身影，我更想讨论镜头为何停在一扇没有打开的门前。空镜头里的等待，往往比答案本身更令人不安。\n\n声音可以先于画面建立一种不可靠的空间：走廊里微小的脚步、反复出现的嗡鸣，或者一个不合时宜的静音。\n\n我的评价待填写：叙事是否成立？恐惧是否来自人物，而不只是音量？看完之后，哪一个细节还留在脑海里？\n\n请替换成真实影片名称与个人观点。',spoiler:false,visible:true},{id:'r2',title:'温柔的表面，不安的回声',film:'影片名称待填写',category:'c4',rating:'待评分',body:'【影评写作示例 · 非真实观影评价】\n\n明亮的房间也可以让人害怕。试着从色彩、构图和角色之间的距离入手，记录一部恐怖片如何一点点改变日常的质感。\n\n在这里写下你对影片的个人评价，可以包含喜欢的镜头、叙事上的遗憾，以及是否愿意推荐。\n\n当前示例未对应任何真实影片，评分待填写。',spoiler:false,visible:true}],resume:[{id:'e1',title:'你的创作方向',period:'个人概况 / 待填写',body:'填写你的专业方向、关注领域与正在寻找的机会。请用真实信息替换这一段提示。',visible:true},{id:'e2',title:'你的经历与项目',period:'经历 / 待填写',body:'按时间记录学习或工作经历，说明承担的角色、完成的工作与实际成果。',visible:true},{id:'e3',title:'你的技能与工具',period:'技能 / 待填写',body:'列出你真正使用过的工具与擅长的能力。这里不预设学历、公司或技能水平。',visible:true}],blocks:[{id:'b1',type:'about',title:'在这里，慢慢认识我。',body:'',visible:true},{id:'b2',type:'music',title:'把想象，写进声音。',body:'',visible:true},{id:'b3',type:'reviews',title:'怕黑，也想多看一眼。',body:'',visible:true},{id:'b4',type:'resume',title:'我走过的，和正在走的。',body:'',visible:true}],comments:[]};
let db=copy(defaults),persistent=true,activeTab='profile',filters={music:'all',reviews:'all'},toastTimer,dialogReturn=null,currentReview=null;
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function storageWarning(text){persistent=false;$('storage-note').textContent=text;$('storage-note').hidden=false}
function validStored(v){if(!v||v.version!==1||!v.profile||!['name','intro','about','contact'].every(k=>typeof v.profile[k]==='string'&&v.profile[k].length<=6000))return false;const schemas={categories:['title','scope'],music:['title','category','body','note'],reviews:['title','film','category','rating','body'],resume:['title','period','body'],blocks:['type','title','body'],comments:['reviewId','nickname','body','date']};return Object.entries(schemas).every(([k,fields])=>Array.isArray(v[k])&&v[k].length<=1000&&new Set(v[k].map(x=>x?.id)).size===v[k].length&&v[k].every(x=>x&&typeof x.id==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(x.id)&&fields.every(f=>typeof x[f]==='string'&&x[f].length<=6000)&&typeof x.visible==='boolean'&&(k!=='categories'||['music','reviews','both'].includes(x.scope))&&(k!=='blocks'||['about','music','reviews','resume','custom'].includes(x.type))));}
try{const raw=localStorage.getItem(KEY);if(raw){const v=JSON.parse(raw);if(!validStored(v))throw Error('schema');db=v}localStorage.setItem(KEY,JSON.stringify(db))}catch(e){storageWarning('本地存储不可用或数据格式异常：当前修改仅在此页面内有效。请导出备份，关闭页面后可能丢失。')}
function persist(){if(!persistent)return false;try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch{storageWarning('浏览器未能保存数据（可能空间已满）。当前修改仅在内存中，请立即导出备份。');return false}}
function saved(){const ok=persist();renderPublic();renderAdmin();notify(ok?'已保存到当前浏览器':'已更新本页；尚未持久保存，请导出备份')}
const categoryName=id=>db.categories.find(c=>c.id===id&&c.visible)?.title||'未分类',categoryOptions=type=>db.categories.filter(c=>c.scope==='both'||c.scope===type),tabs=[['profile','个人资料','PROFILE'],['music','音乐构思','MUSIC'],['reviews','电影评价','CINEMA'],['resume','简历经历','RESUME'],['categories','分类管理','TAXONOMY'],['blocks','区块组件','LAYOUT'],['comments','评论管理','COMMENTS']],types={about:'关于',music:'音乐',reviews:'影评',resume:'简历',custom:'自定义文本'};
const ghost=`<svg viewBox="0 0 260 290" role="img" aria-label="原创小幽灵插画"><defs><linearGradient id="ghost-body" x1="0" y1="0" x2=".9" y2="1"><stop offset="0" stop-color="#ded8ed" stop-opacity=".94"/><stop offset=".65" stop-color="#a89cba" stop-opacity=".8"/><stop offset="1" stop-color="#716681" stop-opacity=".45"/></linearGradient><linearGradient id="ghost-shine"><stop stop-color="#fff" stop-opacity=".5"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient></defs><ellipse cx="131" cy="259" rx="64" ry="9" fill="#050810" opacity=".4"/><path d="M64 141c-5-55 13-100 64-103 49-3 78 34 74 85-3 42 11 67 14 96-17 8-25-12-39-9-14 2-18 28-34 24-15-3-20-22-33-19-18 3-23 23-36 14-13-8-8-26-23-29 9-16 16-36 13-59Z" fill="url(#ghost-body)" stroke="#dbd2e8" stroke-opacity=".45" stroke-width="1.2"/><path d="M77 117c-2-40 19-62 51-65" fill="none" stroke="url(#ghost-shine)" stroke-width="3" stroke-linecap="round"/><ellipse cx="111" cy="130" rx="8" ry="12" fill="#343042"/><ellipse cx="151" cy="125" rx="8" ry="12" fill="#343042"/><path d="M127 151q7 6 12-1" fill="none" stroke="#595064" stroke-width="3" stroke-linecap="round"/><ellipse cx="95" cy="151" rx="9" ry="4" fill="#c797a4" opacity=".45"/><ellipse cx="167" cy="145" rx="9" ry="4" fill="#c797a4" opacity=".45"/><path d="m42 76 3-9 3 9 9 3-9 3-3 9-3-9-9-3Z" fill="#baaac8" opacity=".65"/><path d="m219 157 2-6 2 6 6 2-6 2-2 6-2-6-6-2Z" fill="#b9c9bd" opacity=".7"/></svg>`;
function heading(b,n,en,desc=''){return `<div class="section-heading"><div><div class="eyebrow"><span class="section-number">${String(n).padStart(2,'0')}</span>${en}</div><h2>${esc(b.title)}</h2></div>${desc?`<p>${desc}</p>`:''}</div>`}
function filterHTML(type){const options=categoryOptions(type).filter(c=>c.visible);if(filters[type]!=='all'&&!options.some(c=>c.id===filters[type]))filters[type]='all';return `<div class="filter-row" aria-label="${type==='music'?'音乐':'影评'}分类筛选"><button data-filter="${type}" data-value="all" aria-pressed="${filters[type]==='all'}">全部</button>${options.map(c=>`<button data-filter="${type}" data-value="${c.id}" aria-pressed="${filters[type]===c.id}">${esc(c.title)}</button>`).join('')}</div>`}
function renderBlock(b,n){let contents='',desc='',en='',anchor=b.type==='custom'?'section-'+b.id:b.type;
if(b.type==='about'){en='A LITTLE ABOUT ME';contents=`<div class="about-grid"><p class="about-copy">${esc(db.profile.about)||'自我介绍待填写。'}</p><div class="about-orbits glass"><div class="eyebrow">ROOM FOR POSSIBILITY</div><div class="big-word">Stay curious.</div><p>不急着定义自己。<br>让喜欢的事，慢慢长成自己的样子。</p><div class="chips" style="margin-top:22px"><span class="chip">音乐构思</span><span class="chip">恐怖电影</span><span class="chip">日常灵感</span></div></div></div>`}
if(b.type==='music'){en='SOUNDS, BEFORE THEY BECOME SONGS';desc='一些尚未完成的声音想象。<br>先记录，再让它们慢慢成形。';const items=db.music.filter(x=>x.visible&&(filters.music==='all'||x.category===filters.music));contents=filterHTML('music')+`<div class="music-grid">${items.map((x,i)=>`<article class="music-card glass"><div class="record-art" aria-hidden="true"><div class="record-stamp">SOUND SKETCH / ${String(i+1).padStart(2,'0')}</div><div class="record"><div class="record-label">ORBIT<br>SIDE ${String(i+1).padStart(2,'0')}</div></div><span class="record-note">AN IDEA, NOT A TRACK</span></div><div class="card-body"><span class="chip">${esc(categoryName(x.category))}</span><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><button class="text-button" data-read="music" data-id="${x.id}" aria-label="阅读音乐构思：${esc(x.title)}">阅读构思</button></div></article>`).join('')||'<div class="empty">这里还没有公开的音乐构思。让下一段灵感慢慢到来。</div>'}</div><p class="section-note">仅展示构思文字。唱片为原创 CSS 视觉，不包含音频，也不会模拟播放。</p>`}
if(b.type==='reviews'){en='NOTES FROM THE DARK';desc='关于恐惧、叙事和散场后的余味。<br>主观评价，欢迎留下不同的看法。';const items=db.reviews.filter(x=>x.visible&&(filters.reviews==='all'||x.category===filters.reviews));contents=filterHTML('reviews')+`<div class="film-layout"><div class="ghost-stage glass">${ghost}<div class="ghost-caption"><em>A little fear. A little wonder.</em><p>保持好奇，也保持一点点胆量</p></div></div><div class="review-list">${items.map(x=>`<article class="review-card glass"><div class="review-meta"><span>${esc(categoryName(x.category))}${x.spoiler?' · 含剧透':''}</span><span class="score">${esc(x.rating)}${/^\d/.test(x.rating)?' / 10':''}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.film)} · ${esc(x.body)}</p><div class="review-bottom"><button class="text-button" data-read="reviews" data-id="${x.id}" aria-label="阅读影评并评论：${esc(x.title)}">阅读影评与评论</button><span>${db.comments.filter(c=>c.reviewId===x.id&&c.visible).length} 条本地评论</span></div></article>`).join('')||'<div class="empty">还没有公开的影评。下一次观影后，再来写一点感受。</div>'}</div><p class="section-note">评论按影评分别保存，仅当前浏览器可见，不会发送给站主或其他访客。</p>`}
if(b.type==='resume'){en='A PATH IN PROGRESS';desc='把真实的经历留在这里。<br>不必完美，但每一步都算数。';const items=db.resume.filter(x=>x.visible);contents=`<div class="resume-layout"><aside class="resume-note glass"><div class="eyebrow">THE NEXT CHAPTER</div><h3>Always becoming.</h3><p>个人简历 · 资料待完善。<br>右侧经历可在本地管理中编辑。<br>打印仅包含此简历区块。</p><button data-print>打印 / 存为 PDF ↗</button></aside>${items.length?`<ol class="timeline">${items.map(x=>`<li><small>${esc(x.period)}</small><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></li>`).join('')}</ol>`:'<div class="empty">简历暂无公开条目。</div>'}</div>`}
if(b.type==='custom'){en='MORE IN MY ORBIT';contents=`<div class="custom-copy glass">${esc(b.body)||'此区块还没有内容。'}</div>`}return `<section id="${anchor}" class="section">${heading(b,n,en,desc)}${contents}</section>`}
function renderPublic(){for(const type of ['music','reviews'])if(filters[type]!=='all'&&!categoryOptions(type).some(c=>c.id===filters[type]&&c.visible))filters[type]='all';document.title=(db.profile.name||'未命名的我')+' · PERSONAL ORBIT';$('profile-name').textContent=db.profile.name||'待填写姓名。';$('profile-intro').textContent=db.profile.intro||'个人开场待填写。';$('contact-text').textContent=db.profile.contact||'联系方式待填写。';const blocks=db.blocks.filter(b=>b.visible);$('sections').innerHTML=blocks.map((b,i)=>renderBlock(b,i+1)).join('')||'<p class="empty">内容暂未公开，欢迎稍后再来。</p>';document.querySelectorAll('.main-nav a,.hero-actions a').forEach(a=>{const type=a.hash.slice(1);a.hidden=!blocks.some(b=>b.type===type)});}
function showDialog(title,kicker,html){dialogReturn=document.activeElement;$('modal-title').textContent=title;$('modal-kicker').textContent=kicker;$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal();$('modal-close').focus()}
function closeDialog(){$('modal').close()}
$('modal-close').onclick=closeDialog;$('modal').addEventListener('close',()=>{currentReview=null;if(dialogReturn?.isConnected)dialogReturn.focus();else if(!$('admin').hidden){$('admin-panel').setAttribute('tabindex','-1');$('admin-panel').focus({preventScroll:true})}});$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog()}});
function commentsHTML(id){const comments=db.comments.filter(c=>c.reviewId===id&&c.visible);return comments.map(c=>`<article class="comment"><strong>${esc(c.nickname)}</strong><small>${esc(new Date(c.date).toLocaleDateString('zh-CN'))}</small><p>${esc(c.body)}</p></article>`).join('')||'<div class="comment-empty">这里还没有本地评论。写下你的第一条观感吧。</div>'}
function readItem(type,id){const x=db[type].find(x=>x.id===id&&x.visible);if(!x)return;const review=type==='reviews';currentReview=review?id:null;showDialog(x.title,review?'CINEMA / PERSONAL NOTES':'MUSIC / WORK IN PROGRESS',`<div class="chips"><span class="chip">${esc(categoryName(x.category))}</span><span class="chip">${esc(review?x.film:x.note)}</span>${review?`<span class="chip">${esc(x.rating)}${/^\d/.test(x.rating)?' / 10':''}</span>`:''}</div>${review&&x.spoiler?'<p class="reading-note">剧透提示：以下文字可能透露剧情与结局。</p>':''}<div class="reading-copy">${esc(x.body)||'正文待填写。'}</div>${review?`<section class="comments"><h3>留一点你的看法。</h3><p>仅保存在当前浏览器，不跨设备，不会发送给站主。请勿留下敏感信息。</p><div id="comment-list">${commentsHTML(id)}</div><form id="comment-form" class="comment-form" data-review-id="${id}"><div class="form-grid"><label class="field">昵称<input name="nickname" required maxlength="30" autocomplete="nickname" placeholder="怎么称呼你？"></label><label class="field">你的评论<textarea name="body" required maxlength="1200" rows="4" placeholder="聊聊这篇影评，或者你的不同感受。"></textarea><small>最多 1,200 字；只支持纯文本。</small></label></div><div class="form-actions"><span class="form-message" id="comment-message" role="status"></span><button class="primary" type="submit">保存本地评论 ↗</button></div></form></section>`:'<p class="reading-note">当前仅有文字构思，未附音频。此页面没有播放功能。</p>'}`)}
$('sections').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.filter){filters[b.dataset.filter]=b.dataset.value;renderPublic();document.querySelector(`[data-filter="${b.dataset.filter}"][data-value="${b.dataset.value}"]`)?.focus()}if(b.dataset.read)readItem(b.dataset.read,b.dataset.id);if(b.hasAttribute('data-print'))window.print()});
$('modal-content').addEventListener('submit',e=>{if(e.target.id!=='comment-form')return;e.preventDefault();const f=e.target;if(!f.reportValidity())return;const nickname=f.elements.nickname.value.trim(),body=f.elements.body.value.trim(),reviewId=f.dataset.reviewId;if(!nickname||!body){$('comment-message').textContent='昵称和评论不能只包含空格。';return}if(nickname.length>30||body.length>1200)return;if(!db.reviews.some(r=>r.id===reviewId&&r.visible))return;if(db.comments.length>=1000){$('comment-message').textContent='本地评论已达上限，请先在管理中整理。';return}db.comments.push({id:uid(),reviewId,nickname,body,date:new Date().toISOString(),visible:true});const ok=persist();renderPublic();$('comment-list').innerHTML=commentsHTML(reviewId);f.reset();$('comment-message').textContent=ok?'已保存，仅当前浏览器可见。':'仅保存在本页内存中，请导出备份。';});
function field(label,name,value='',options={}){const full=options.full?' full':'',max=options.max||120;let control;if(options.select){control=`<select name="${name}" ${options.required===false?'':'required'}>${options.select.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`}else if(options.area){control=`<textarea name="${name}" maxlength="${max}" rows="${options.rows||5}" ${options.required===false?'':'required'}>${esc(value)}</textarea>`}else{control=`<input name="${name}" value="${esc(value)}" maxlength="${max}" ${options.required===false?'':'required'}>`}return `<label class="field${full}">${label}${control}${options.hint?`<small>${options.hint}</small>`:''}</label>`}
function profileForm(){return `<form id="profile-form" class="profile-form glass"><div class="form-grid">${field('显示姓名','name',db.profile.name,{max:30,full:true,required:false})}${field('开场介绍','intro',db.profile.intro,{max:400,area:true,full:true,required:false})}${field('关于我的正文','about',db.profile.about,{max:2000,area:true,full:true,required:false})}${field('公开联系方式 / 结尾文字','contact',db.profile.contact,{max:200,full:true,required:false,hint:'只填写愿意公开的信息；不会自动生成外部链接。'})}</div><div class="form-actions"><button type="button" class="danger" data-clear-profile>清空资料</button><button class="primary" type="submit">保存个人资料</button></div></form>`}
function renderAdmin(){if(!$('admin'))return;$('admin-nav').innerHTML=tabs.map(([key,label,en])=>`<button data-tab="${key}" aria-current="${activeTab===key?'page':'false'}">${label}<small>${en}</small></button>`).join('');const title=tabs.find(x=>x[0]===activeTab)[1];let help={profile:'资料修改后即时同步到前台。空内容会显示待填写提示。',music:'仅支持文字构思，无音频播放。可分类、排序、隐藏或删除。',reviews:'每篇影评有独立评论区。删除影评也会删除其本地评论。',resume:'维护真实经历与技能；按列表顺序展示并可浏览器打印。',categories:'分类可关联音乐、影评或两者。隐藏后前台标签显示未分类；删除会解除关联，不删除作品。',blocks:'上下调整前台区块顺序。支持新增自定义文本区块；删除展示区块不会删除其中的作品数据。',comments:'按所属影评管理本地留言。这里不是云端访客评论后台。'}[activeTab];let content=activeTab==='profile'?profileForm():adminRows();$('admin-panel').innerHTML=`<div class="admin-panel-heading"><h2>${title}</h2>${activeTab==='profile'?'':`<button class="primary" data-new>+ 新增${activeTab==='comments'?'本地评论':activeTab==='blocks'?'区块':activeTab==='categories'?'分类':'条目'}</button>`}</div><p class="admin-help">${help}</p>${content}`}
function adminRows(){const items=db[activeTab];return items.length?items.map((x,i)=>{let name=x.title,info='';if(activeTab==='comments'){name=x.nickname+' · '+(db.reviews.find(r=>r.id===x.reviewId)?.title||'影评已删除');info=x.body.slice(0,110)}if(activeTab==='music'||activeTab==='reviews')info=categoryName(x.category)+(activeTab==='reviews'?' · '+x.film:' · '+x.note);if(activeTab==='resume')info=x.period;if(activeTab==='categories')info={music:'音乐',reviews:'影评',both:'音乐与影评'}[x.scope];if(activeTab==='blocks')info=types[x.type];return `<article class="admin-row"><div class="admin-row-info"><h3>${esc(name)}</h3><p>${esc(info)}${!x.visible?' · 已隐藏':''}</p></div><div class="admin-row-actions"><button data-edit="${x.id}">编辑</button><button data-toggle="${x.id}" aria-label="${x.visible?'隐藏':'显示'} ${esc(name)}">${x.visible?'隐藏':'显示'}</button><button data-move="${x.id}" data-direction="-1" ${i===0?'disabled':''} aria-label="上移 ${esc(name)}">↑</button><button data-move="${x.id}" data-direction="1" ${i===items.length-1?'disabled':''} aria-label="下移 ${esc(name)}">↓</button><button class="danger" data-delete="${x.id}">删除</button></div></article>`}).join(''):'<div class="empty">这里还是空的。点击右上角新增第一条内容。</div>'}
function editor(type,id){const existing=id?db[type].find(x=>x.id===id):null;if(id&&!existing)return;const x=existing||{},v=x.visible!==false;let fields='';
if(type==='music'||type==='reviews'){fields=field('标题','title',x.title,{max:100,full:true})+field('分类','category',x.category||'',{select:[['','未分类'],...categoryOptions(type).map(c=>[c.id,c.title+(c.visible?'':'（已隐藏）')])],required:false});if(type==='music')fields+=field('状态说明','note',x.note||'构思笔记 · 尚无音频',{max:80});else fields+=field('影片名称','film',x.film,{max:100})+field('个人评分','rating',x.rating||'待评分',{select:[['待评分','待评分'],...Array.from({length:21},(_,i)=>[String(i/2),String(i/2)+' / 10'])]});fields+=field(type==='music'?'构思正文':'个人影评','body',x.body,{area:true,full:true,max:6000,rows:9,hint:'最多 6,000 字；纯文本显示，不执行 HTML。'});if(type==='reviews')fields+=`<label class="check-field"><input type="checkbox" name="spoiler" ${x.spoiler?'checked':''}>包含剧透（阅读页会显示提示）</label>`;}
if(type==='resume')fields=field('经历 / 技能标题','title',x.title,{max:100,full:true})+field('时间或分组','period',x.period,{max:100,full:true})+field('详细说明','body',x.body,{area:true,full:true,max:3000});
if(type==='categories')fields=field('分类名称','title',x.title,{max:50})+field('适用内容','scope',x.scope||'music',{select:[['music','音乐'],['reviews','影评'],['both','音乐与影评']],hint:'修改范围后，不再适用的作品会自动解除分类关联。'});
if(type==='blocks'){const available=Object.entries(types).filter(([k])=>k==='custom'||!db.blocks.some(b=>b.type===k&&b.id!==id));fields=field('区块类型','type',x.type||'custom',{select:available,hint:'标准区块每种仅可添加一个；作品数据独立保存。'})+field('区块标题','title',x.title,{max:100})+field('自定义文本正文','body',x.body,{area:true,full:true,max:6000,required:false,hint:'仅自定义文本区块使用此字段；标准区块从相应内容栏目读取。'});}
if(type==='comments'){if(!db.reviews.length){notify('请先创建一篇影评，再添加评论。');return}fields=field('所属影评','reviewId',x.reviewId||db.reviews[0].id,{select:db.reviews.map(r=>[r.id,r.title]),full:true})+field('昵称','nickname',x.nickname,{max:30,full:true})+field('评论正文','body',x.body,{area:true,full:true,max:1200});}
showDialog((id?'编辑':'新增')+tabs.find(t=>t[0]===type)[1],'LOCAL EDITOR / 仅当前浏览器',`<form id="editor-form" data-type="${type}" data-id="${id||''}"><div class="form-grid">${fields}</div><label class="check-field"><input type="checkbox" name="visible" ${v?'checked':''}>在前台显示</label><div class="form-actions"><span id="editor-message" class="form-message" role="status"></span><button type="button" data-cancel>取消</button><button class="primary" type="submit">保存</button></div></form>`);}
function confirmDialog(title,text,fn){showDialog(title,'CONFIRM / 请确认',`<p class="reading-copy">${esc(text)}</p><div class="form-actions"><button data-cancel>取消</button><button class="danger" id="confirm-action">确认删除</button></div>`);$('confirm-action').onclick=()=>{fn();closeDialog();saved()};}
$('admin-nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(!b)return;activeTab=b.dataset.tab;renderAdmin();$('admin-nav').querySelector('[aria-current=page]')?.focus()});
$('admin-panel').addEventListener('submit',e=>{if(e.target.id!=='profile-form')return;e.preventDefault();if(!e.target.reportValidity())return;const f=new FormData(e.target);for(const k of ['name','intro','about','contact'])db.profile[k]=String(f.get(k)||'').trim();saved()});
$('admin-panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-new'))return editor(activeTab);if(b.dataset.edit)return editor(activeTab,b.dataset.edit);if(b.hasAttribute('data-clear-profile'))return confirmDialog('清空个人资料？','姓名、开场、关于与联系方式将被清空。作品和简历不会删除。',()=>{for(const k of Object.keys(db.profile))db.profile[k]=''});if(b.dataset.toggle){const x=db[activeTab].find(x=>x.id===b.dataset.toggle);x.visible=!x.visible;saved();return}if(b.dataset.move){const i=db[activeTab].findIndex(x=>x.id===b.dataset.move),j=i+Number(b.dataset.direction);if(j<0||j>=db[activeTab].length)return;[db[activeTab][i],db[activeTab][j]]=[db[activeTab][j],db[activeTab][i]];saved();return}if(b.dataset.delete){const type=activeTab,id=b.dataset.delete,x=db[type].find(x=>x.id===id);let note=type==='reviews'?'此影评及其全部本地评论将永久删除。':type==='categories'?'分类将删除，关联作品会变为未分类，作品本身会保留。':type==='blocks'?'只删除该展示区块，不删除作品、评论或资料。可重新添加标准区块。':'此内容将永久从当前浏览器数据中删除。';confirmDialog('删除“'+(x.title||x.nickname)+'”？',note,()=>{db[type]=db[type].filter(x=>x.id!==id);if(type==='reviews')db.comments=db.comments.filter(c=>c.reviewId!==id);if(type==='categories')for(const group of ['music','reviews'])db[group].forEach(x=>{if(x.category===id)x.category=''})})}});
$('modal-content').addEventListener('click',e=>{if(e.target.closest('[data-cancel]'))closeDialog()});
$('modal-content').addEventListener('submit',e=>{const form=e.target;if(form.id!=='editor-form')return;e.preventDefault();if(!form.reportValidity())return;const type=form.dataset.type,id=form.dataset.id,existing=db[type].find(x=>x.id===id),data=new FormData(form),x={...(existing||{}),id:id||uid(),visible:data.has('visible')};const schema={music:['title','category','note','body'],reviews:['title','film','category','rating','body'],resume:['title','period','body'],categories:['title','scope'],blocks:['title','type','body'],comments:['nickname','reviewId','body']}[type];for(const key of schema)x[key]=String(data.get(key)||'').trim();for(const el of form.querySelectorAll('[required]')){if(!el.value.trim()){$('editor-message').textContent='必填内容不能只包含空格。';el.focus();return}}if(!existing&&db[type].length>=1000){$('editor-message').textContent='条目数量已达本地演示上限，请先整理。';return}if(type==='reviews')x.spoiler=data.has('spoiler');if(type==='comments')x.date=existing?.date||new Date().toISOString();if(type==='categories'){if(db.categories.some(c=>c.id!==id&&c.title===x.title)){ $('editor-message').textContent='已有同名分类，请使用不同名称。';return}for(const g of ['music','reviews'])if(x.scope!=='both'&&x.scope!==g)db[g].forEach(a=>{if(a.category===id)a.category=''})}if(type==='blocks'&&x.type!=='custom'&&db.blocks.some(b=>b.id!==id&&b.type===x.type)){$('editor-message').textContent='该标准区块已存在。';return}if(existing)db[type][db[type].findIndex(x=>x.id===id)]=x;else db[type].push(x);closeDialog();saved();});
$('export-data').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='personal-orbit-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('已请求下载 JSON 备份；文件可能包含你的个人资料与评论。')};
let renderScene=()=>{},setSceneActivity=()=>{};
function route(){const admin=location.hash==='#admin';$('home').hidden=admin;$('admin').hidden=!admin;$('footer').hidden=admin;if(admin)renderAdmin();document.body.classList.toggle('motion-held',admin);setSceneActivity();if(admin)$('admin').focus({preventScroll:true});else{renderScene();const target=document.getElementById(location.hash.slice(1));if(target)setTimeout(()=>target.scrollIntoView({behavior:'auto'}),0)}}
window.addEventListener('hashchange',route);renderPublic();renderAdmin();
// Keep the original W21 geometry and runtime. Customize only this instance's palette and surrounding geometry.
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),canvas=$('scene'),item=CreativeRuntime.items().find(x=>x.id==='W21'),baseCreate=item.create;
item.create=T=>{const instance=baseCreate(T);instance.scene.background=new T.Color('#090e17');const rings=new T.Group();instance.scene.add(rings);for(let n=0;n<2;n++){const points=[];for(let j=0;j<=180;j++){const a=j/180*Math.PI*2;points.push(new T.Vector3(Math.cos(a)*(5.7+n*.5),Math.sin(a)*(3.4+n*.25),0))}const line=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:n?'#b1a3cd':'#9acaba',transparent:true,opacity:.16}));line.rotation.set(.45+n*.4,-.25+n*.4,-.35+n*.65);line.position.z=-2;rings.add(line)}const satellite=new T.Mesh(new T.SphereGeometry(.075,12,8),new T.MeshBasicMaterial({color:'#bba9c9'}));rings.add(satellite);const update=instance.update;instance.update=(t,p,i)=>{update(t,p,i);satellite.position.set(Math.cos(t*.35)*5.4,Math.sin(t*.35)*3.3,-1.8);rings.rotation.y=Math.sin(t*.15)*.08;};return instance};
const state={...CreativeRuntime.input(),duoUi:true,duoMode:'wallpaper',duoZoom:.85,duoAspect:1.2,duoOpening:155/180,dragX:-.22,dragY:.1};const params={title:'保持好奇',subtitle:'A little room for possibility.',accent:'#688e83',intensity:.35,seed:42};let paused=reduced.matches,auto=true,visible=true,sceneFailed=false,time=1,raf=0,last=0,drag=null;
function motionUI(){document.body.classList.toggle('paused',paused);$('motion-toggle').textContent=paused?'恢复动画':'暂停动画';$('motion-toggle').setAttribute('aria-pressed',String(paused));$('auto-fold').setAttribute('aria-pressed',String(auto));$('auto-fold').textContent=auto?'自动':'手动'}
function paint(){if(sceneFailed||$('home').hidden)return;try{if(auto)state.duoOpening=.6+.36*(.5+.5*Math.cos(time*.48));state.duoAspect=canvas.clientWidth/Math.max(1,canvas.clientHeight);CreativeRuntime.render(item,canvas,time,params,state);const angle=Math.round(state.duoOpening*180);$('fold').value=angle;$('fold-output').textContent=angle+'°';canvas.dataset.angle=String(angle);canvas.dataset.rotation=state.dragX.toFixed(3);canvas.dataset.frame=time.toFixed(3)}catch(e){sceneFailed=true;$('scene-error').textContent='当前浏览器无法显示 WebGL 2 三维场景。请开启硬件加速后刷新；正文、影评评论与本地管理仍可正常使用。';$('scene-error').hidden=false;for(const id of ['fold','auto-fold','reset-scene'])$(id).disabled=true;console.info('3D fallback:',e.message)}}
function canAnimate(){return !paused&&!sceneFailed&&visible&&!document.hidden&&!$('home').hidden}
function tick(now){raf=0;if(!canAnimate())return;if(!last||now-last>=1000/30){if(last)time+=Math.min(.08,(now-last)/1000);last=now;paint()}if(canAnimate())raf=requestAnimationFrame(tick)}
function syncAnimation(){cancelAnimationFrame(raf);raf=0;last=0;motionUI();if(canAnimate())raf=requestAnimationFrame(tick)}
setSceneActivity=syncAnimation;renderScene=()=>{resize();syncAnimation()};
function resize(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);paint()}
$('motion-toggle').onclick=()=>{paused=!paused;syncAnimation();notify(paused?'已暂停全站自动动画；手动交互仍然可用。':reduced.matches?'三维自动动画已恢复；系统减少动态效果仍关闭装饰动画。':'已恢复全站动画。')};reduced.addEventListener('change',e=>{if(e.matches)paused=true;syncAnimation()});
$('fold').addEventListener('input',()=>{auto=false;state.duoOpening=Number($('fold').value)/180;paint();motionUI()});$('auto-fold').onclick=()=>{auto=!auto;paint();motionUI()};
function reset(){state.dragX=-.22;state.dragY=.1;state.duoZoom=.85;state.duoOpening=155/180;time=1;paint()}
$('reset-scene').onclick=reset;const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||e.isPrimary===false)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,dx:state.dragX,dy:state.dragY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;state.dragX=clamp(drag.dx+(e.clientX-drag.x)/canvas.clientWidth*3,-2,2);state.dragY=clamp(drag.dy+(e.clientY-drag.y)/canvas.clientHeight*2,-1,1);paint()});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>{drag=null});canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home')reset();else{state.dragX=clamp(state.dragX+(e.key==='ArrowLeft'?-.12:e.key==='ArrowRight'?.12:0),-2,2);state.dragY=clamp(state.dragY+(e.key==='ArrowUp'?-.12:e.key==='ArrowDown'?.12:0),-1,1);paint()}});
new ResizeObserver(resize).observe(canvas);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;syncAnimation()}).observe(canvas);document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('motion-held',document.hidden||!$('admin').hidden);syncAnimation()});window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));route();resize();motionUI();syncAnimation();
})();

